stages:
  preprocess:
    cmd: python src/preprocess.py --train_input data/train.csv --test_input data/test.csv --output_path data/processed
    deps:
    - data/test.csv
    - data/train.csv
    - src/preprocess.py
    outs:
    - data/processed
  train:
    cmd: python src/train.py --train_data data/processed/train --model_out model/model.joblib
    deps:
    - data/processed
    - src/train.py
    outs:
    - model/model.joblib
    metrics:
    - metrics.json:
        cache: false