stages:
  preprocess:
    cmd: python src/data_processing.py --train_input data/raw/train.csv 
      --test_input data/raw/test.csv --output_path data/processed
    deps:
    - data/raw/test.csv
    - data/raw/train.csv
    - src/data_processing.py
    outs:
    - data/processed
    frozen: true
  train:
    cmd: python src/train.py --train_data data/processed/train --model_out 
      model/model.joblib
    deps:
    - data/processed
    - src/train.py
    outs:
    - model/model.joblib
    metrics:
    - metrics.json:
        cache: false
