# Add a profile selector at the top
experiment_profile: low_resource
# Parameters for Spark experiments. We can define multiple configurations here.

spark_configs:
  baseline:
    driver_memory: 2g
    executor_cores: 1
    shuffle_partitions: 10

  high_memory:
    driver_memory: 4g
    executor_cores: 1
    shuffle_partitions: 10

  more_cores:
    driver_memory: 2g
    executor_cores: 2
    shuffle_partitions: 20

  low_resource:
    driver_memory: 1g
    executor_cores: 1
    shuffle_partitions: 5

  high_parallelism:
    driver_memory: 4g
    executor_cores: 4
    shuffle_partitions: 100

