aname: MLOps CI/CD Pipeline

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up DVC
      uses: iterative/dvc-action@v1

    - name: Configure DVC Google App Credentials
      run: |
        dvc remote modify myremote gdrive_client_id ${{ secrets.GDRIVE_CLIENT_ID }}
        dvc remote modify myremote gdrive_client_secret ${{ secrets.GDRIVE_CLIENT_SECRET }}

    - name: Authenticate DVC with Google User Token
      run: |
        mkdir -p .dvc/tmp
        echo '${{ secrets.GDRIVE_CREDENTIALS_DATA }}' > .dvc/tmp/gdrive-user-credentials.json

    - name: Pull DVC-tracked data
      run: dvc pull

    - name: Reproduce DVC pipeline
      run: dvc repro

    # --- NEW STEPS FOR API TESTING ---
    - name: Start FastAPI server in background
      run: uvicorn api:app --host 0.0.0.0 --port 8000 &

    - name: Wait for API to be ready
      run: sleep 15 # Give the server a moment to start up

    - name: Run Pytest on the API
      run: pytest -v