name: MLOps CI/CD Pipeline (with Debugging)

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up DVC
      uses: iterative/dvc-action@v1

    - name: Configure DVC Google App Credentials
      run: |
        dvc remote modify myremote gdrive_client_id ${{ secrets.GDRIVE_CLIENT_ID }}
        dvc remote modify myremote gdrive_client_secret ${{ secrets.GDRIVE_CLIENT_SECRET }}

    - name: Authenticate DVC with Google User Token
      run: |
        mkdir -p .dvc/tmp
        echo '${{ secrets.GDRIVE_CREDENTIALS_DATA }}' > .dvc/tmp/gdrive-user-credentials.json

    # --- NEW DEBUGGING STEPS ---
    - name: "[DEBUG] Verify DVC Config File"
      run: |
        echo "--- Contents of .dvc/config ---"
        cat .dvc/config
        echo "---------------------------------"

    - name: "[DEBUG] Verify Credentials File"
      run: |
        echo "--- Verifying existence of credentials file ---"
        ls -l .dvc/tmp/
        echo "-----------------------------------------------"

    - name: Pull DVC-tracked data
      run: dvc pull -v # Added -v for verbose output

    - name: Reproduce DVC pipeline
      run: dvc repro

    - name: Run Pytest on the API
      run: |
        uvicorn api:app --host 0.0.0.0 --port 8000 &
        sleep 15
        pytest -v