name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # DVC Studio remote uses S3, so we need to install the s3 dependency
        pip install "dvc[s3]"
        pip install -r requirements.txt

    - name: Set up DVC
      uses: iterative/dvc-action@v1

    # DVC will automatically use the DVC_STUDIO_TOKEN secret. No other steps are needed.
    - name: Pull DVC-tracked data
      env:
        DVC_STUDIO_TOKEN: ${{ secrets.DVC_STUDIO_TOKEN }}
      run: dvc pull

    - name: Reproduce DVC pipeline
      env:
        DVC_STUDIO_TOKEN: ${{ secrets.DVC_STUDIO_TOKEN }}
      run: dvc repro

    - name: Run Pytest on the API
      env:
        DVC_STUDIO_TOKEN: ${{ secrets.DVC_STUDIO_TOKEN }}
      run: |
        uvicorn api:app --host 0.0.0.0 --port 8000 &
        sleep 15
        pytest -v